CREATE TABLE IF NOT EXISTS user_permission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  resource VARCHAR(64) NOT NULL,
  action VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_permission_user
  ON user_permission(username);
